#######################
#data base
#######################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://dev-ddrd-management.crqzg9d1kmc5.ap-northeast-2.rds.amazonaws.com:3306/dev_ddrd?characterEncoding=utf8
    password: ddrd-management
#######################
#log setting
#######################
logging:
  config:
    classpath: logback-setting.xml
  file:
    name: ../logs/local_log
    path: /logs/local_log
    error: ../logs/error_log
  level:
    root: info
