server:
  port: 3000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
    profiles:
      active: local
    devtools:
      livereload:
        enabled: true
    thymeleaf:
      cache: false
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          use_sql_comments: true
          default_batch_fetch_size: 1000
      hibernate:
        ddl-auto: update

# jwt.secret.key의 값은 256bit 이상이어야 합니다.
jwt:
  secret:
    key: y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaPdSgVkYp2s

mybatis:
  mapper-locations: /mybatis/**/*.xml
  configuration:
    config-location: mybatis.xml
    map-underscore-to-camel-case: true
  type-aliases-package: com/ddrd/management/**/domain
