#######################
#data base
#######################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://dev-ddrd-management.crqzg9d1kmc5.ap-northeast-2.rds.amazonaws.com:3306/dev_ddrd?characterEncoding=utf8
    password: ddrd-management
  sql:
    init:
      mode: always
#######################
#log setting
#######################
log:
  level: info
  config:
    filename: local_log  # 로깅 파일 위치이다.
    path: ${user.dir}/Work/99.side/01.ddrd/01.workspace/logs
